spring.application.name=promdetal-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/promdetal
spring.datasource.username=postgres
spring.datasource.password=14022005Ae!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/promdetal