spring.application.name=promdetal-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/promdetal
spring.datasource.username=postgres
spring.datasource.password=14022005Ae!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/promdetal
server.port=8080
spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=promdetal_site@mail.ru
spring.mail.password=VKy9vsTFJSX15GhkEq2a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mail.ru
